[0m14:14:38.303260 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000202253814C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002022432E070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002022432EE20>]}


============================== 14:14:38.309518 | 6d36e0f5-7021-4dea-9d2f-5ce2b07a9e72 ==============================
[0m14:14:38.309518 [info ] [MainThread]: Running with dbt=1.7.4
[0m14:14:38.310522 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\HTK1511\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m14:14:38.313983 [info ] [MainThread]: dbt version: 1.7.4
[0m14:14:38.315017 [info ] [MainThread]: python version: 3.8.10
[0m14:14:38.316561 [info ] [MainThread]: python path: c:\users\htk1511\appdata\local\programs\python\python38\python.exe
[0m14:14:38.317591 [info ] [MainThread]: os info: Windows-10-10.0.26100-SP0
[0m14:14:39.163987 [info ] [MainThread]: Using profiles dir at C:\Users\HTK1511\.dbt
[0m14:14:39.165003 [info ] [MainThread]: Using profiles.yml file at C:\Users\HTK1511\.dbt\profiles.yml
[0m14:14:39.165003 [info ] [MainThread]: Using dbt_project.yml file at C:\Git\sb_loja_virtual\dbt_project.yml
[0m14:14:39.166514 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:14:39.166849 [debug] [MainThread]: Command `dbt debug` failed at 14:14:39.166849 after 0.96 seconds
[0m14:14:39.166849 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000202253814C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020224324070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020228984BE0>]}
[0m14:14:39.167858 [debug] [MainThread]: Flushing usage events
[0m14:18:39.277476 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022913DD2430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002291673E3A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022912D7ED00>]}


============================== 14:18:39.281493 | 9b999c01-84b4-4348-83a0-06841fdca6f8 ==============================
[0m14:18:39.281493 [info ] [MainThread]: Running with dbt=1.7.4
[0m14:18:39.281493 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\HTK1511\\.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m14:18:39.282477 [info ] [MainThread]: dbt version: 1.7.4
[0m14:18:39.282477 [info ] [MainThread]: python version: 3.8.10
[0m14:18:39.282477 [info ] [MainThread]: python path: c:\users\htk1511\appdata\local\programs\python\python38\python.exe
[0m14:18:39.283478 [info ] [MainThread]: os info: Windows-10-10.0.26100-SP0
[0m14:18:39.752090 [info ] [MainThread]: Using profiles dir at C:\Users\HTK1511\.dbt
[0m14:18:39.753106 [info ] [MainThread]: Using profiles.yml file at C:\Users\HTK1511\.dbt\profiles.yml
[0m14:18:39.754095 [info ] [MainThread]: Using dbt_project.yml file at C:\Git\sb_loja_virtual\dbt_project.yml
[0m14:18:39.754606 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:18:39.756113 [debug] [MainThread]: Command `dbt debug` failed at 14:18:39.754606 after 0.55 seconds
[0m14:18:39.756113 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022913DD2430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022917385820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000229173ADDC0>]}
[0m14:18:39.756113 [debug] [MainThread]: Flushing usage events
[0m14:20:38.968472 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC188AD400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC191BD2E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC17835D90>]}


============================== 14:20:38.972537 | 0894cefc-5ec4-48d6-be64-d27b24e235a6 ==============================
[0m14:20:38.972537 [info ] [MainThread]: Running with dbt=1.7.4
[0m14:20:38.972537 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\HTK1511\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt debug --profiles-dir C:\\Users\\HTK1511\\.dbt', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:20:38.972537 [info ] [MainThread]: dbt version: 1.7.4
[0m14:20:38.974046 [info ] [MainThread]: python version: 3.8.10
[0m14:20:38.974046 [info ] [MainThread]: python path: c:\users\htk1511\appdata\local\programs\python\python38\python.exe
[0m14:20:38.974046 [info ] [MainThread]: os info: Windows-10-10.0.26100-SP0
[0m14:20:39.325216 [info ] [MainThread]: Using profiles dir at C:\Users\HTK1511\.dbt
[0m14:20:39.325216 [info ] [MainThread]: Using profiles.yml file at C:\Users\HTK1511\.dbt\profiles.yml
[0m14:20:39.325216 [info ] [MainThread]: Using dbt_project.yml file at C:\Git\sb_loja_virtual\dbt_project.yml
[0m14:20:39.326222 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:20:39.327216 [debug] [MainThread]: Command `dbt debug` failed at 14:20:39.327216 after 0.42 seconds
[0m14:20:39.327216 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC188AD400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC1BE47880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC1BE65A90>]}
[0m14:20:39.327216 [debug] [MainThread]: Flushing usage events
